name: Node CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run unit tests
        run: |
          npm install
          npm test
        env:
          CI: true
      - name: Integration tests
        run: |
          docker-compose up -d
          ./waitForEmulator.sh
          npm run test:integration
          docker-compose down
      - uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - uses: actions/gcloud/cli@master
        with:
          args: app deploy --version slippers
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
          CLOUDSDK_CORE_PROJECT: ${{ secrets.PROJECT_NAME }}

#
